name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: bash build.sh
      - name: Upload artifact windows 386
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-windows-386
          path: bin/windows/386/TimeElapsed.exe
      - name: Upload artifact windows amd64
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-windows-amd64
          path: bin/windows/amd64/TimeElapsed.exe
      - name: Upload artifact linux 386
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-linux-386
          path: bin/linux/386/TimeElapsed
      - name: Upload artifact linux amd64
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-linux-amd64
          path: bin/linux/amd64/TimeElapsed
      - name: Upload artifact linux arm
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-linux-arm
          path: bin/linux/arm/TimeElapsed
      - name: Upload artifact linux arm64
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-linux-arm64
          path: bin/linux/arm64/TimeElapsed
