name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: bash build.sh
      - name: Upload artifact windows 386
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-windows-386
          path: bin/windows/386/TimeElapsed.exe
      - name: Upload artifact windows amd64
        uses: actions/upload-artifact@v6
        with:
          name: timeelapsed-windows-amd64
          path: bin/windows/amd64/TimeElapsed.exe
